# Generated by Django 5.1.6 on 2025-02-13 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyPlayedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=200)),
                ('played_at', models.DateTimeField()),
                ('track_name', models.CharField(blank=True, max_length=255, null=True)),
                ('artists', models.JSONField(blank=True, default=list, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played_tracks', to='spotify_data.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningHistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('top_artists_data', models.JSONField(default=list)),
                ('top_tracks_data', models.JSONField(default=list)),
                ('total_listening_time_ms', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history_snapshots', to='spotify_data.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TopTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('artists', models.JSONField(default=list)),
                ('album_name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_tracks', to='spotify_data.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'track_id')},
            },
        ),
        migrations.CreateModel(
            name='TopArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('genres', models.JSONField(default=list)),
                ('popularity', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_artists', to='spotify_data.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'artist_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('artists', models.JSONField(default=list)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tracks', to='spotify_data.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'track_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('artists', models.JSONField(default=list)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_albums', to='spotify_data.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'album_id')},
            },
        ),
    ]
